#!/bin/bash

# here we are trying to add a meaningful temp message for a commit #

branch_name=`git branch | grep '*' | cut -c3-`
new_files=`git status | grep 'file:' | cut -c14-`
modified_files=`git status | grep 'modified:' | cut -c14-`
deleted_files=`git status | grep 'deleted:' | cut -c14-`

commit_msg="commit msg for $branch_name "

if [[ $new_files ]]; then
    commit_msg+=" - added $new_files"
fi

if [[ $modified_files ]]; then
    commit_msg+=" - modified $modified_files"
fi

if [[ $deleted_files ]]; then
    commit_msg+=" - deleted $deleted_files"
fi

echo $commit_msg > $1