#!/bin/bash

#this is initially created to perform checkstyle before allowing
#user to commit

current_path=`pwd`
pom_file=`find $current_path -type f -name "pom.xml"`
echo "pom file path - $pom_file - EOF"
if [[ $pom_file ]]; then
  mvn checkstyle:check
fi
