#!/bin/bash

current_path=`pwd`
pom_file=`find $current_path -type f -name "pom.xml"`
if [[ $pom_file ]]; then
  echo "============== Performing mvn checkstyle."
  mvn checkstyle:check
else 
  echo "============== No pre-commit action to perform."
fi
